# Generated by Django 4.2.19 on 2025-02-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='words_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
